### ISSUE TITLE
SURF not available,stitching.stitching_error.StitchingError: No match exceeds the given confidence theshold.

### ISSUE THREAD

**Issue by monkeycc** [lukasalexanderweber/stitching#17]
```
import stitching


stitcher = stitching.Stitcher()
panorama = stitcher.stitch(["F:/2022/PJ/123/1.jpg", "F:/2022/PJ/123/2.jpg", "F:/2022/PJ/123/3.jpg"])
```

python 4.py

```
SURF not available
Traceback (most recent call last):
  File "4.py", line 5, in <module>
    panorama = stitcher.stitch(["F:/2022/PJ/123/1.jpg", "F:/2022/PJ/123/2.jpg", "F:/2022/PJ/123/3.jpg"])
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 87, in stitch
    imgs, features, matches = self.subset(imgs, features, matches)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 133, in subset
    matches,
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\subsetter.py", line 28, in subset
    indices = self.get_indices_to_keep(features, matches)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\subsetter.py", line 53, in get_indices_to_keep
    raise StitchingError("No match exceeds the " "given confidence theshold.")
stitching.stitching_error.StitchingError: No match exceeds the given confidence theshold.
```

**Comment by lukasalexanderweber** [comment]
Try

Stitcher(confidence_threshold=0)

**Comment by monkeycc** [comment]
`stitcher = stitching.Stitcher(confidence_threshold=0)`

```

python 4.py

SURF not available
Traceback (most recent call last):
  File "4.py", line 4, in <module>
    panorama = stitcher.stitch(["F:/2022/PJ/123/1.jpg", "F:/2022/PJ/123/2.jpg", "F:/2022/PJ/123/3.jpg"])
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 89, in stitch
    cameras = self.refine_camera_parameters(features, matches, cameras)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 142, in refine_camera_parameters
    return self.camera_adjuster.adjust(features, matches, cameras)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\camera_adjuster.py", line 44, in adjust
    b, cameras = self.adjuster.apply(features, pairwise_matches, estimated_cameras)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\compat_ptsetreg.cpp:125: error: (-215:Assertion failed) !err.empty() in function 'CvLevMarq::update'
```

**Comment by lukasalexanderweber** [comment]
You sure your Images have an overlapping area?

**Comment by monkeycc** [comment]
yes

![ok](https://user-images.githubusercontent.com/6490927/181800247-42ff6fb0-1791-497b-9ca6-bc086b2f8b40.jpg)

**Comment by lukasalexanderweber** [comment]
Then wave_correct_kind='no'

**Comment by monkeycc** [comment]
```python
import stitching

stitcher = stitching.Stitcher(confidence_threshold=0,wave_correct_kind='no')
panorama = stitcher.stitch(["F:/2022/PJ/123/1.jpg", "F:/2022/PJ/123/2.jpg", "F:/2022/PJ/123/3.jpg"])
```

python 4.py
```
SURF not available
Traceback (most recent call last):
  File "4.py", line 4, in <module>
    panorama = stitcher.stitch(["F:/2022/PJ/123/1.jpg", "F:/2022/PJ/123/2.jpg", "F:/2022/PJ/123/3.jpg"])
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 89, in stitch
    cameras = self.refine_camera_parameters(features, matches, cameras)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 142, in refine_camera_parameters
    return self.camera_adjuster.adjust(features, matches, cameras)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\camera_adjuster.py", line 44, in adjust
    b, cameras = self.adjuster.apply(features, pairwise_matches, estimated_cameras)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\compat_ptsetreg.cpp:125: error: (-215:Assertion failed) !err.empty() in function 'CvLevMarq::update'
```

**Comment by lukasalexanderweber** [comment]
adjuster='no'

**Comment by monkeycc** [comment]
`stitcher = stitching.Stitcher(confidence_threshold=0,adjuster='no')`


```
SURF not available
OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueNDRangeKernel('buildWarpSphericalMaps', dims=2, globalsize=154624x26536x1, localsize=NULL) sync=true
Traceback (most recent call last):
  File "4.py", line 4, in <module>
    panorama = stitcher.stitch(["F:/2022/PJ/123/1.jpg", "F:/2022/PJ/123/2.jpg", "F:/2022/PJ/123/3.jpg"])
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 112, in stitch
    self.blend_images(imgs, seam_masks, corners)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 225, in blend_images
    for idx, (img, mask, corner) in enumerate(zip(imgs, masks, corners)):
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 197, in compensate_exposure_errors
    for idx, (corner, img) in enumerate(zip(corners, imgs)):
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\cropper.py", line 66, in crop_images
    for idx, img in enumerate(imgs):
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\warper.py", line 41, in warp_images
    yield self.warp_image(img, camera, aspect)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\warper.py", line 50, in warp_image
    cv.BORDER_REFLECT,
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\ocl.cpp:5954: error: (-220:Unknown error code -220) OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call: clEnqueueReadBuffer(q, handle=000001F9A410A8E0, CL_TRUE, 0, sz=16382294196, data=000001FE02803080, 0, 0, 0) in function 'cv::ocl::OpenCLAllocator::map'

```

**Comment by monkeycc** [comment]
OpenCL ??

`cv2.ocl.setUseOpenCL(False)`
```

SURF not available
Traceback (most recent call last):
  File "4.py", line 6, in <module>
    panorama = stitcher.stitch(["F:/2022/PJ/123/1.jpg", "F:/2022/PJ/123/2.jpg", "F:/2022/PJ/123/3.jpg"])
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 112, in stitch
    self.blend_images(imgs, seam_masks, corners)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 225, in blend_images
    for idx, (img, mask, corner) in enumerate(zip(imgs, masks, corners)):
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\stitcher.py", line 197, in compensate_exposure_errors
    for idx, (corner, img) in enumerate(zip(corners, imgs)):
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\cropper.py", line 66, in crop_images
    for idx, img in enumerate(imgs):
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\warper.py", line 41, in warp_images
    yield self.warp_image(img, camera, aspect)
  File "D:\anaconda3\envs\stitching\lib\site-packages\stitching\warper.py", line 50, in warp_image
    cv.BORDER_REFLECT,
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:1724: error: (-215:Assertion failed) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function 'cv::remap'
```

**Comment by lukasalexanderweber** [comment]
The Default medium and low megapix are not suited for such big images

**Comment by monkeycc** [comment]
Requirements cannot affect image details
So it can't be reduced

Thank you for your help and reply
I'll have a test tomorrow morning
good night

**Comment by lukasalexanderweber** [comment]
No the Final Resolution ist not reduced

**Comment by lukasalexanderweber** [comment]
Its just for the intermediate steps. Please follow the Tutorial

**Comment by monkeycc** [comment]
Unfortunately, it didn't succeed

Can I pack the pictures for you

**Comment by lukasalexanderweber** [comment]
I can have a try If you want

**Comment by monkeycc** [comment]
Please send your email

**Comment by lukasalexanderweber** [comment]
l.alex.w@web.de

**Comment by Wurenkang** [comment]
Did you succeed in the end?
