### ISSUE TITLE
The 'parallel' target is not currently supported on 32 bit hardware.

### ISSUE THREAD

**Issue by minwook96** [lukasalexanderweber/stitching#24]
os : windows 10
cpu : Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs)
gpu : gtx 1660ti
python 3.8.6
usage : stitch imgs/*

(venv) C:\Users\HwangMW\Desktop\stitching>stitch imgs/*
stitching imgs\weir_1.jpg imgs\weir_2.jpg imgs\weir_3.jpg imgs\weir_noise.jpg into result.jpg
Traceback (most recent call last):
  File "C:\Users\HwangMW\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HwangMW\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HwangMW\Desktop\stitching\venv\Scripts\stitch.exe\__main__.py", line 7, in <module>
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\stitching\cli\stitch.py", line 278, in main     
    panorama = stitcher.stitch(img_names)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\stitching\stitcher.py", line 100, in stitch     
    self.prepare_cropper(imgs, masks, corners, sizes)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\stitching\stitcher.py", line 176, in prepare_cropper
    self.cropper.prepare(imgs, masks, corners, sizes)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\stitching\cropper.py", line 57, in prepare
    lir = self.estimate_largest_interior_rectangle(mask)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\stitching\cropper.py", line 94, in estimate_largest_interior_rectangle
    import largestinteriorrectangle
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\largestinteriorrectangle\__init__.py", line 1, in <module>
    from .lir import lir
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\largestinteriorrectangle\lir.py", line 1, in <module>
    from .lir_basis import largest_interior_rectangle as lir_basis
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\largestinteriorrectangle\lir_basis.py", line 13, in <module>
    def horizontal_adjacency(grid):
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\decorators.py", line 219, in wrapper
    disp.compile(sig)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler.py", line 499, in _compile_core
    raise e
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler_machinery.py", line 368, in run
    raise patched_exception
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\typed_passes.py", line 394, in run_pass
    lower.lower()
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\lowering.py", line 168, in lower
    self.lower_normal_function(self.fndesc)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\lowering.py", line 222, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\lowering.py", line 251, in lower_function_body
    self.lower_block(block)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\lowering.py", line 265, in lower_block
    self.lower_inst(inst)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\core\lowering.py", line 567, in lower_inst
    func(self, inst)
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\parfors\parfor_lowering.py", line 58, in _lower_parfor_parallel
    ensure_parallel_support()
  File "c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\numba\parfors\parfor.py", line 5016, in ensure_parallel_support
    raise errors.UnsupportedParforsError(msg)
numba.core.errors.UnsupportedParforsError: Failed in nopython mode pipeline (step: native lowering)
The 'parallel' target is not currently supported on 32 bit hardware.
During: lowering "id=0[LoopNest(index_variable = parfor_index.10, range = (0, grid_size0.1, 1)), LoopNest(index_variable = parfor_index.11, range = (0, grid_size1.2, 1))]{127: <ir.Block at c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\largestinteriorrectangle\lir_basis.py (14)>}Var($parfor_index_tuple_var.17, lir_basis.py:14)" at c:\users\hwangmw\desktop\stitching\venv\lib\site-packages\largestinteriorrectangle\lir_basis.py (14)

This is the result of running after installation.
Why is this?

**Comment by lukasalexanderweber** [comment]
Numba apperently won't support (Windows) 32bit machines for parallel execution.

You need to try without cropping:

`stitch imgs/* --no-crop`

For a sollution to crop the image after stitching you might refer to https://github.com/lukasalexanderweber/stitching_tutorial/issues/11#issue-1339829830

**Comment by minwook96** [comment]
Then, is there any way to work properly in Windows without using numba?

**Comment by lukasalexanderweber** [comment]
Here is how you do it without numba

`stitch imgs/* --no-crop`

**Comment by lukasalexanderweber** [comment]
Any reproducers please let me know. Please refer to https://github.com/lukasalexanderweber/stitching/pull/25 for an alternative cropping sollution!
