### ISSUE TITLE
Camera parameters adjusting failed.

### ISSUE THREAD

**Issue by phenolophthaleinum** [lukasalexanderweber/stitching#35]
I am trying to stitch about 30 images of almost flat ground. Images were taken top-down, and are overlapping by about 30%. I am generating a match file, in which almost all images are somewhat connected, but after about 4-5 minutes of running, the following error appears:
```Traceback (most recent call last):
  File ".\texture_stitching.py", line 19, in <module>
    panorama = stitcher.stitch(imgs)
  File "C:\Users\Maciej\anaconda3\lib\site-packages\stitching\stitcher.py", line 94, in stitch
    cameras = self.refine_camera_parameters(features, matches, cameras)
  File "C:\Users\Maciej\anaconda3\lib\site-packages\stitching\stitcher.py", line 147, in refine_camera_parameters
    return self.camera_adjuster.adjust(features, matches, cameras)
  File "C:\Users\Maciej\anaconda3\lib\site-packages\stitching\camera_adjuster.py", line 49, in adjust
    raise StitchingError("Camera parameters adjusting failed.")
stitching.stitching_error.StitchingError: Camera parameters adjusting failed.
```

I am using python 3.8 and newest version of opencv.
Here is an example photo and match file:
```
graph matches_graph{
"grass001_scan_0001.jpg" -- "grass001_scan_0008.jpg"[label="Nm=22, Ni=6, C=0.410959"];
"grass001_scan_0001.jpg" -- "grass001_scan_0032.jpg"[label="Nm=6, Ni=4, C=0.408163"];
"grass001_scan_0002.jpg" -- "grass001_scan_0003.jpg"[label="Nm=34, Ni=17, C=0.934066"];
"grass001_scan_0002.jpg" -- "grass001_scan_0007.jpg"[label="Nm=45, Ni=23, C=1.06977"];
"grass001_scan_0002.jpg" -- "grass001_scan_0008.jpg"[label="Nm=22, Ni=8, C=0.547945"];
"grass001_scan_0002.jpg" -- "grass001_scan_0009.jpg"[label="Nm=14, Ni=5, C=0.409836"];
"grass001_scan_0002.jpg" -- "grass001_scan_0021.jpg"[label="Nm=6, Ni=4, C=0.408163"];
"grass001_scan_0003.jpg" -- "grass001_scan_0004.jpg"[label="Nm=42, Ni=16, C=0.776699"];
"grass001_scan_0003.jpg" -- "grass001_scan_0006.jpg"[label="Nm=47, Ni=32, C=1.44796"];
"grass001_scan_0004.jpg" -- "grass001_scan_0005.jpg"[label="Nm=37, Ni=19, C=0.994764"];
"grass001_scan_0004.jpg" -- "grass001_scan_0026.jpg"[label="Nm=10, Ni=5, C=0.454545"];
"grass001_scan_0005.jpg" -- "grass001_scan_0011.jpg"[label="Nm=23, Ni=8, C=0.536913"];
"grass001_scan_0005.jpg" -- "grass001_scan_0012.jpg"[label="Nm=50, Ni=26, C=1.13043"];
"grass001_scan_0005.jpg" -- "grass001_scan_0016.jpg"[label="Nm=14, Ni=5, C=0.409836"];
"grass001_scan_0005.jpg" -- "grass001_scan_0018.jpg"[label="Nm=14, Ni=5, C=0.409836"];
"grass001_scan_0005.jpg" -- "grass001_scan_0027.jpg"[label="Nm=6, Ni=4, C=0.408163"];
"grass001_scan_0006.jpg" -- "grass001_scan_0024.jpg"[label="Nm=11, Ni=5, C=0.442478"];
"grass001_scan_0006.jpg" -- "grass001_scan_0030.jpg"[label="Nm=13, Ni=5, C=0.420168"];
"grass001_scan_0007.jpg" -- "grass001_scan_0010.jpg"[label="Nm=39, Ni=20, C=1.01523"];
"grass001_scan_0007.jpg" -- "grass001_scan_0015.jpg"[label="Nm=14, Ni=5, C=0.409836"];
"grass001_scan_0010.jpg" -- "grass001_scan_0020.jpg"[label="Nm=13, Ni=5, C=0.420168"];
"grass001_scan_0011.jpg" -- "grass001_scan_0013.jpg"[label="Nm=20, Ni=9, C=0.642857"];
"grass001_scan_0011.jpg" -- "grass001_scan_0014.jpg"[label="Nm=35, Ni=17, C=0.918919"];
"grass001_scan_0012.jpg" -- "grass001_scan_0017.jpg"[label="Nm=6, Ni=4, C=0.408163"];
"grass001_scan_0012.jpg" -- "grass001_scan_0023.jpg"[label="Nm=6, Ni=4, C=0.408163"];
"grass001_scan_0013.jpg" -- "grass001_scan_0022.jpg"[label="Nm=14, Ni=5, C=0.409836"];
"grass001_scan_0014.jpg" -- "grass001_scan_0019.jpg"[label="Nm=25, Ni=11, C=0.709677"];
"grass001_scan_0017.jpg" -- "grass001_scan_0028.jpg"[label="Nm=14, Ni=5, C=0.409836"];
"grass001_scan_0021.jpg" -- "grass001_scan_0029.jpg"[label="Nm=14, Ni=5, C=0.409836"];
"grass001_scan_0024.jpg" -- "grass001_scan_0025.jpg"[label="Nm=34, Ni=17, C=0.934066"];
"grass001_scan_0026.jpg" -- "grass001_scan_0031.jpg"[label="Nm=25, Ni=15, C=0.967742"];
```

![grass001_scan_0011_prev](https://user-images.githubusercontent.com/14911686/201471996-db35aa11-f837-412b-bbc8-c264dbcf215c.jpg)

I have also tinkered with different detectors (orb, akaze, sift - best matches with orb I believe) and thresholds, but with no luck. Is there anything I can do with it?

**Comment by lukasalexanderweber** [comment]
have you tried without adjusting?

`--adjuster no`

**Comment by phenolophthaleinum** [comment]
Will try. In the meantime, I have tried affine and it produced a decent picture so it's not that bad
