### ISSUE TITLE
Skipped test_stitcher_boat1 and test_stitcher_boat2 (test_stitcher.py) don't pass anymore

### ISSUE THREAD

**Issue by chufall** [lukasalexanderweber/stitching#58]
Hi, thank you for your great works!

I have run the test_stitcher.py  , but the test_stitcher_boat1 and test_stitcher_boat2 gave the error as the  following :
----------------------------------------------------------------------------------------------------------------
E
Error
Traceback (most recent call last):
  File "C:\Users\chqiu\anaconda3\envs\deepface\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\chqiu\anaconda3\envs\deepface\lib\unittest\case.py", line 628, in run
    testMethod()
  File "D:\2.1\stitching\stitching\tests\test_stitcher.py", line 74, in test_stitcher_boat2
    "boat6.jpg",
  File "D:\2.1\stitching\stitching\stitching\stitcher.py", line 94, in stitch
    cameras = self.refine_camera_parameters(features, matches, cameras)
  File "D:\2.1\stitching\stitching\stitching\stitcher.py", line 147, in refine_camera_parameters
    return self.camera_adjuster.adjust(features, matches, cameras)
  File "D:\2.1\stitching\stitching\stitching\camera_adjuster.py", line 49, in adjust
    raise StitchingError("Camera parameters adjusting failed.")
stitching.stitching_error.StitchingError: Camera parameters adjusting failed.
----------------------------------------------------------------------------------------------------------------

So how to fix it? thanks a lot
QC

**Comment by lukasalexanderweber** [comment]
thank you for the feedback! Indeed, the tests also fail on my machine. I need to check which change introduced the bugs. The moral? Don't skip tests -.-

**Comment by lukasalexanderweber** [comment]
fixed with af8a4673a3b9056dd0da92c62b81b8e472701ca4. It was introduced in 4d1563a42368759059d3bd1c7646ac034a0dac47
